//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QueryBuilder1._0
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QUERY_BILDER_DBEntities : DbContext
    {
        public QUERY_BILDER_DBEntities()
            : base("name=QUERY_BILDER_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EHTO> EHTO { get; set; }
        public virtual DbSet<MAARITYS> MAARITYS { get; set; }
        public virtual DbSet<OPERAATTORI> OPERAATTORI { get; set; }
        public virtual DbSet<SQL_EHTO> SQL_EHTO { get; set; }
        public virtual DbSet<SQL_MAARITYS> SQL_MAARITYS { get; set; }
        public virtual DbSet<SQL_OPERAATTORI> SQL_OPERAATTORI { get; set; }
        public virtual DbSet<SQL_VALINTAOPERAATTORI> SQL_VALINTAOPERAATTORI { get; set; }
        public virtual DbSet<VALINTAOPERAATTORI> VALINTAOPERAATTORI { get; set; }
        public virtual DbSet<kysely> kysely { get; set; }
    }
}
