//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QueryBuilder1._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class EHTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EHTO()
        {
            this.SQL_EHTO = new HashSet<SQL_EHTO>();
        }
    
        public double ID { get; set; }
        public string EHTO1 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SQL_EHTO> SQL_EHTO { get; set; }
    }
}
