//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QueryBuilder1._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAARITYS
    {
        public double ID { get; set; }
        public string MAARITYS_EHTO { get; set; }
        public Nullable<double> VALINTA_ID { get; set; }
    
        public virtual VALINTAOPERAATTORI VALINTAOPERAATTORI { get; set; }
    }
}
