//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QueryBuilder1._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class SQL_VALINTAOPERAATTORI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SQL_VALINTAOPERAATTORI()
        {
            this.SQL_MAARITYS = new HashSet<SQL_MAARITYS>();
        }
    
        public double SQLValintaOperaattori_ID { get; set; }
        public string SQL { get; set; }
        public Nullable<double> ValintaOperaattori_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SQL_MAARITYS> SQL_MAARITYS { get; set; }
        public virtual VALINTAOPERAATTORI VALINTAOPERAATTORI { get; set; }
    }
}
