//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QueryBuilder1._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class VALINTAOPERAATTORI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VALINTAOPERAATTORI()
        {
            this.MAARITYS = new HashSet<MAARITYS>();
            this.SQL_VALINTAOPERAATTORI = new HashSet<SQL_VALINTAOPERAATTORI>();
        }
    
        public double ValintaOperaattori_ID { get; set; }
        public string VALINTAOPERAATTORI1 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAARITYS> MAARITYS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SQL_VALINTAOPERAATTORI> SQL_VALINTAOPERAATTORI { get; set; }
    }
}
